### ISSUE TITLE
Allow a secret to exist on multiple namespaces

### ISSUE THREAD

**Issue by digiserg** [digitalis-io/vals-operator#30]
The change would allow the same secret to being synced to multiple namespaces. This can be very useful for secrets such as private docker registries. The new schema could look like the example below:

```yaml
---
apiVersion: digitalis.io/v1
kind: ValsSecret
metadata:
  name: private-registry
spec:
  type: kubernetes.io/dockerconfigjson
  namespaces:
    - one
    - two
    - three
  data:
    auth:
      ref: "ref+vault://secret/registry/dockerconfigjson"
      encoding: text
```
