### ISSUE TITLE
Permit combing secrets with raw data

### ISSUE THREAD

**Issue by digiserg** [digitalis-io/vals-operator#35]
For example,

```yaml
---
apiVersion: digitalis.io/v1
kind: ValsSecret
metadata:
  name: my-secret
spec:
  ttl: 3600       # Optional, default is 0. The secret will be checked at every "reconcile period". See below.
  type: Opaque    # Default type, others supported
  data:
    username:
      ref: ref+vault://secret/username
      encoding: text
    password:
      ref: ref+vault://secret/password
      encoding: text
    server:
      plain: my-server.com
```

**Comment by digiserg** [comment]
I just realised this already works:

```yaml
  data:
    username:
      ref: plain-text-username
      encoding: text
```

As the `ref+` prefix is not set, it won't be process by the underlying `vals`. 

@rgooding Would you happy with just documenting the feature or do you think we should create a separate config key for plain text/raw data?
