### ISSUE TITLE
Template field missing in helmchart CRDs

### ISSUE THREAD

**Issue by nerok** [digitalis-io/vals-operator#43]
I tried using the templating for ValsSecret when I noticed that my CRDs which was installed with helm hasn't been updated. And after looking at the chart in this repo it seems that the CRD might not have been regenerated after templating was added. Would it be possible to regenerate the CRD for the helmchart, as I would very much like to try out the new templating feature.

**Comment by jspruyt** [comment]
To test it, you can manually edit the CustomResourceDefinition (valssecrets.digitalis.io)

add
```yaml
template:
    additionalProperties:
      type: string
    type: object
```

to `spec.versions[v1].schema.openAPIV3Schema.properties.spec.properties`
