### ISSUE TITLE
Can't use 1password secrets?

### ISSUE THREAD

**Issue by shakefu** [digitalis-io/vals-operator#78]
I am trying to use vals-operator to pull secrets from 1password, but getting the following error: 

```
Failed to get secrets from secrets store expand op://Engineering/k8s-test-secret/credential: no provider registered for scheme "op"
```

On version 0.7.9 of the chart:

```yaml
src:
  repoUrl: "https://digitalis-io.github.io/helm-charts"
  chart: vals-operator
  targetRevision: 0.7.9
  releaseName: vals-operator

helm:
  values: |
    secretEnv:
    - secretRef:
        name: vals-onepassword
```

With a manually created secret passed into the chart:

```yaml
# $ kubectl get secret -n vals-operator vals-onepassword -o yaml
apiVersion: v1
data:
  OP_SERVICE_ACCOUNT_TOKEN: <HIDDEN>
kind: Secret
metadata:
  creationTimestamp: "2024-07-22T23:25:07Z"
  name: vals-onepassword
  namespace: vals-operator
  resourceVersion: "92572"
  uid: 7444c6ab-4f83-4589-84d8-bdc1f807b39b
type: Opaque
```

... and I verified the chart is correctly rendering that secretRef into the Pod:

```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: '2024-07-22T23:31:29Z'
  generateName: vals-operator-7bd87cffb8-
  labels:
    app.kubernetes.io/instance: vals-operator
    app.kubernetes.io/name: vals-operator
    pod-template-hash: 7bd87cffb8
  name: vals-operator-7bd87cffb8-4jd7t
  namespace: vals-operator
spec:
  containers:
    - envFrom:
        - secretRef:
            name: vals-onepassword
      image: 'ghcr.io/digitalis-io/vals-operator:v0.7.9'
      imagePullPolicy: IfNotPresent
      name: vals-operator
# ...
```

... and here's the secret definition:

```yaml
apiVersion: digitalis.io/v1
kind: ValsSecret
metadata:
  name: k8s-test-secret
spec:
  type: Opaque
  data:
    username:
      ref: ref+op://Engineering/k8s-test-secret/username
      encoding: text
    credential:
      ref: ref+op://Engineering/k8s-test-secret/credential
      encoding: text
```

Is there something I'm missing here? Or is 1password not supported in the Operator?
